version: '3.3'
services:
    node:
        build: '.'
        restart: always
        user: node
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
        volumes:
            - './api-server:/home/node/app'
            - './.env:/home/node/app/.env'
#            - '/home/node/app/node_modules'
        ports:
            - '8081:8081'
        command: 'npm start'
        networks:
          - local-network
    static:
        image: 'nginx:latest'
        restart: always
        volumes:
            - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './static:/usr/share/nginx/html'
        ports:
            - '80:80'
            - '443:443'
        networks:
          - local-network
networks:
  local-network: